#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const sourcePath = resolve(here, 'tokens.json')
const outputPath = resolve(here, 'tokens.css')
const source = JSON.parse(readFileSync(sourcePath, 'utf8'))
const tokens = new Map()

function flatten(value, path = []) {
  if (value && typeof value === 'object' && !Array.isArray(value)) {
    for (const [key, child] of Object.entries(value)) flatten(child, [...path, key])
    return
  }
  if (typeof value !== 'string') throw new Error(`Token ${path.join('.')} must be a string`)
  tokens.set(path.join('.'), { path, value })
}

flatten(source)

function resolveToken(name, table = tokens, stack = []) {
  const token = table.get(name)
  if (!token) throw new Error(`Missing token reference: ${name}`)
  if (stack.includes(name)) throw new Error(`Token cycle: ${[...stack, name].join(' -> ')}`)
  const match = /^\{([^}]+)\}$/.exec(token.value)
  if (!match) return token.value
  return resolveToken(match[1], table, [...stack, name])
}

const resolved = new Map()
for (const name of tokens.keys()) resolved.set(name, resolveToken(name))

/**
 * The dark palette is a parallel table of colour primitives, not a second set of
 * semantic tokens. Every token is re-resolved against a table whose
 * `primitive.color.*` entries point at `primitive.dark.color.*`, so a semantic
 * token written once in tokens.json lands on the right colour in both themes
 * and a dark key that is missing falls back to the light value.
 */
const darkTokens = new Map(tokens)
for (const [name, entry] of tokens) {
  if (!name.startsWith('primitive.color.')) continue
  const dark = tokens.get(`primitive.dark.color.${name.slice('primitive.color.'.length)}`)
  if (dark) darkTokens.set(name, dark)
}
const darkResolved = new Map()
for (const name of darkTokens.keys()) darkResolved.set(name, resolveToken(name, darkTokens))

const isEmittedToken = (name) => !name.startsWith('legacy.') && !name.startsWith('primitive.dark.')

/**
 * The names `styles.css` still consumes keep their unprefixed declarations, so
 * they are re-declared per theme rather than once in `:root`. A dark block that
 * omitted them would leave a light canvas and dark text behind in every part of
 * the workbench that still reads them.
 */
const legacyDeclarations = (table) =>
  [...table.entries()]
    .filter(([name]) => name.startsWith('legacy.'))
    .map(([name, value]) => `  ${name.slice('legacy.'.length)}: ${value};`)

const primitiveAndSemantic = [...resolved.entries()].filter(([name]) => !name.startsWith('legacy.'))
const themeEntries = primitiveAndSemantic
  .filter(([name]) =>
    /^(semantic\.(surface|text|border|action|selection|focus|feedback|diff))\./.test(name),
  )
  .map(([name]) => {
    const key = name.slice('semantic.'.length).split('.').join('-')
    return `  --color-${key}: var(--gs-${name.replaceAll('.', '-')});`
  })
  .concat([
    '  --font-sans: var(--gs-semantic-font-sans);',
    '  --font-mono: var(--gs-semantic-font-mono);',
    '  --text-body: var(--gs-semantic-type-body-size);',
    '  --text-label: var(--gs-semantic-type-label-size);',
    '  --text-metadata: var(--gs-semantic-type-metadata-size);',
    '  --radius-control: var(--gs-semantic-radius-control);',
    '  --radius-item: var(--gs-semantic-radius-item);',
    '  --radius-workbench: var(--gs-semantic-radius-workbench);',
    '  --spacing-1: var(--gs-semantic-space-1);',
    '  --spacing-2: var(--gs-semantic-space-2);',
    '  --spacing-3: var(--gs-semantic-space-3);',
    '  --spacing-4: var(--gs-semantic-space-4);',
    '  --shadow-small: var(--gs-semantic-elevation-small);',
    '  --shadow-medium: var(--gs-semantic-elevation-medium);',
    '  --shadow-large: var(--gs-semantic-elevation-large);',
  ])

const declaration = (name, value) => `  --gs-${name.replaceAll('.', '-')}: ${value};`
const darkDeclarations = [...darkResolved.entries()]
  .filter(([name]) => isEmittedToken(name))
  .map(([name, value]) => declaration(name, value))
const darkLegacyDeclarations = legacyDeclarations(darkResolved)

const generated = [
  '/* This file is generated by design-system/generate-tokens.mjs from tokens.json. */',
  '/* Edit tokens.json, then run npm run tokens:generate. */',
  '',
  '@theme inline {',
  ...themeEntries,
  '}',
  '',
  '/* Light is the default. `system` follows the operating system in the media',
  '   query below, so a stored theme of "system" tracks a later change with no',
  '   script involved. */',
  ':root,',
  "[data-gs-theme='light'] {",
  ...primitiveAndSemantic.map(([name, value]) => declaration(name, value)),
  ...legacyDeclarations(resolved),
  '}',
  '',
  "[data-gs-theme='dark'] {",
  ...darkDeclarations,
  ...darkLegacyDeclarations,
  '}',
  '',
  '@media (prefers-color-scheme: dark) {',
  "  [data-gs-theme='system'] {",
  ...darkDeclarations.map((line) => `  ${line}`),
  ...darkLegacyDeclarations.map((line) => `  ${line}`),
  '  }',
  '}',
  '',
  '@media (prefers-reduced-motion: reduce) {',
  '  :root {',
  '    --gs-semantic-motion-fast: var(--gs-semantic-motion-reduced);',
  '    --gs-semantic-motion-standard: var(--gs-semantic-motion-reduced);',
  '    --gs-semantic-motion-deliberate: var(--gs-semantic-motion-reduced);',
  '  }',
  '}',
  '',
].join('\n')

if (process.argv.includes('--check')) {
  const current = readFileSync(outputPath, 'utf8')
  if (current !== generated) {
    console.error('tokens.css is out of date; run npm run tokens:generate')
    process.exitCode = 1
  }
} else {
  writeFileSync(outputPath, generated)
  console.log(`Generated ${outputPath}`)
}
